import React, { useState } from 'react';
import { Button, ImageBackground, StyleSheet, Text, View } from 'react-native';
import hintergrundbild from './rainbow.png';

export default function App() {
  const wortListe = [
    { wort: 'adäquat', definition: 'angemessen, entsprechend' },
    { wort: "Koc", definition: "loyal, verlässlich, vertrauenswürdig, großherzig" },
    { wort: "adäquat", definition: "angemessen, passend" },
    { wort: "affektiert", definition: "gekünstelt, geziert" },
    { wort: "affirmativ", definition: "bejahend, zustimmend" },
    { wort: "aggregieren", definition: "zusammenfügen, vereinen" },
    { wort: "aggressiv", definition: "angriffslustig, kämpferisch" },
    { wort: "agil", definition: "beweglich, wendig" },
    { wort: "akribisch", definition: "höchst sorgfältig, äußerst gründlich" },
    { wort: "akut", definition: "plötzlich auftretend, dringlich" },
    { wort: "akzentuieren", definition: "betonen, hervorheben" },
    { wort: "altruistisch", definition: "selbstlos, uneigennützig" },
    { wort: "anachronistisch", definition: "zeitlich unpassend, veraltet" },
    { wort: "analog", definition: "entsprechend, ähnlich" },
    { wort: "anonym", definition: "namenlos, unbekannt" },
    { wort: "antagonistisch", definition: "gegensätzlich, widerstreitend" },
    { wort: "apathisch", definition: "teilnahmslos, abgestumpft" },
    { wort: "arriviert", definition: "angesehen, -" },
    { wort: "assertiv", definition: "selbstbewusst, durchsetzungsfähig" },
    { wort: "assoziieren", definition: "in Verbindung bringen, assoziieren" },
    { wort: "asymmetrisch", definition: "ungleich, -" },
    { wort: "authentifizieren", definition: "bestätigen, nachweisen" },
    { wort: "authentisch", definition: "echt, glaubwürdig" },
    { wort: "autokratisch", definition: "selbstherrlich, -" },
    { wort: "banal", definition: "nichts besonderes, gewöhnlich" },
    { wort: "brachial", definition: "handgreiflich, mit roher Körperkraft" },
    { wort: "charismatisch", definition: "ausstrahlend, überzeugend" },
    { wort: "dediziert", definition: "jemandem gewidmet, zugeeignet" },
    { wort: "definitiv", definition: "endgültig, abschließend" },
    { wort: "dekadent", definition: "verfallen, -" },
    { wort: "deklarativ", definition: "erklärend, -" },
    { wort: "designiert", definition: "für etwas vorgesehen, -" },
    { wort: "desolat", definition: "trostlos, traurig" },
    { wort: "destruktiv", definition: "zerstörerisch, schädlich" },
    { wort: "deterministisch", definition: "vorherbestimmt, zwangsläufig" },
    { wort: "dezidiert", definition: "eindeutig entscheiden, energisch" },
    { wort: "diabolisch", definition: "teuflisch, -" },
    { wort: "diametral", definition: "entgegengesetzt, gegensätzlich" },
    { wort: "differenziert", definition: "fein abgestuft, nuanciert" },
    { wort: "diffizil", definition: "schwierig, kompliziert" },
    { wort: "diffus", definition: "unklar, ungeordnet" },
    { wort: "dilettantisch", definition: "amateurhaft, unprofessionell" },
    { wort: "diskreditieren", definition: "herabsetzen, -" },
    { wort: "diskursiv", definition: "argumentativ, erörternd" },
    { wort: "diskutabel", definition: "erörterungswert, -" },
    { wort: "distinguiert", definition: "betont, -" },
    { wort: "dubios", definition: "zweifelhaft, fragwürdig" },
    { wort: "dystopisch", definition: "pessimistisch, apokalyptisch" },
    { wort: "effektiv", definition: "wirksam, erfolgreich" },
    { wort: "egalitär", definition: "gleichberechtigt, auf Gleichheit basierend" },
    { wort: "eklatant", definition: "offensichtlich, -" },
    { wort: "ekstatisch", definition: "verzückt, -" },
    { wort: "elegant", definition: "geschmackvoll, -" },
    { wort: "elitär", definition: "exklusiv, privilegiert" },
    { wort: "eloquent", definition: "redegewandt, -" },
    { wort: "emanzipatorisch", definition: "befreiend, befreiend" },
    { wort: "eminent", definition: "hervorragend, -" },
    { wort: "emphatisch", definition: "einfühlsam, mitfühlend" },
    { wort: "engagiert", definition: "leidenschaftlich, -" },
    { wort: "enigmatisch", definition: "rätselhaft, -" },
    { wort: "ephemeral", definition: "vergänglich, flüchtig" },
    { wort: "epochal", definition: "bahnbrechend, -" },
    { wort: "eremitisch", definition: "zurückgezogen, einsam" },
    { wort: "erfassen", definition: "begreifen, -" },
    { wort: "erhaben", definition: "erhaben, -" },
    { wort: "erhellend", definition: "aufklärend, -" },
    { wort: "erläutern", definition: "erklären, -" },
    { wort: "erleuchtet", definition: "aufgeklärt, -" },
    { wort: "erschöpfend", definition: "vollständig, -" },
    { wort: "esoterisch", definition: "geheimnisvoll, mystisch" },
    { wort: "ethnisch", definition: "kulturell, volkszugehörig" },
    { wort: "evokativ", definition: "evozierend, hervorrufend" },
    { wort: "exaltiert", definition: "überschwänglich, -" },
    { wort: "exponentiell", definition: "stark, -" },
    { wort: "extensiv", definition: "umfassend, -" },
    { wort: "extravagant", definition: "ausgefallen, exzentrisch" },
    { wort: "exzentrisch", definition: "ausgefallen, eigenwillig" },
    { wort: "facettenreich", definition: "vielschichtig, -" },
    { wort: "faszinierend", definition: "beeindruckend, anziehend" },
    { wort: "fatal", definition: "verhängnisvoll, -" },
    { wort: "fatalistisch", definition: "schicksalsergeben, vielschichtig" },
    { wort: "frivol", definition: "leichtfertig, unbeschwert" },
    { wort: "fundamental", definition: "grundlegend, -" },
    { wort: "funktional", definition: "zweckmäßig, praktisch" },
    { wort: "fürsorglich", definition: "fürsorglich, -" },
    { wort: "fürsprechen", definition: "unterstützen, verteidigen" },
    { wort: "furtiv", definition: "heimlich, -" },
    { wort: "fusionieren", definition: "verschmelzen, -" },
    { wort: "gallant", definition: "galant, -" },
    { wort: "gallig", definition: "bissig, sarkastisch" },
    { wort: "gefällig", definition: "angenehm, -" },
    { wort: "genial", definition: "brilliant, herausragend" },
    { wort: "genügsam", definition: "bescheiden, -" },
    { wort: "gerissen", definition: "schlau, apathisch" },
    { wort: "gewissenhaft", definition: "gewissenhaft, -" },
    { wort: "gewitzt", definition: "schlau, -" },
    { wort: "gigantisch", definition: "riesig, -" },
    { wort: "gourmet", definition: "Feinschmecker, -" },
    { wort: "graduell", definition: "stufenweise, allmählich" },
    { wort: "gratuit", definition: "kostenlos, -" },
    { wort: "gravitätisch", definition: "würdevoll, -" },
    { wort: "grazil", definition: "zierlich, -" },
    { wort: "gregorisch", definition: "regelmäßig, -" },
    { wort: "grenzenlos", definition: "unendlich, -" },
    { wort: "grüblerisch", definition: "nachdenklich, -" },
    { wort: "harmonisch", definition: "ausgewogen, stimmig" },
    { wort: "hedonistisch", definition: "genussvoll, lustbetont" },
    { wort: "hegemonial", definition: "vorherrschend, -" },
    { wort: "hermetisch", definition: "undurchdringlich, -" },
    { wort: "heroisch", definition: "heldenhaft, mutig" },
    { wort: "heterodox", definition: "abweichend, unkonventionell" },
    { wort: "heterogen", definition: "verschiedenartig, -" },
    { wort: "hierarchisch", definition: "geordnet, -" },
    { wort: "hochmütig", definition: "überheblich, -" },
    { wort: "hygienisch", definition: "sauber, -" },
    { wort: "hypnotisch", definition: "faszinierend, -" },
    { wort: "idealisieren", definition: "idealisieren, -" },
    { wort: "ikonisch", definition: "symbolisch, -" },
    { wort: "ikonoklastisch", definition: "bildstürmerisch, rebellisch" },
    { wort: "illustrieren", definition: "veranschaulichen, -" },
    { wort: "immanent", definition: "innewohnend, -" },
    { wort: "impertinent", definition: "unverschämt, frech" },
    { wort: "improvisieren", definition: "spontan handeln, -" },
    { wort: "impulsiv", definition: "impulsiv, unüberlegt" },
    { wort: "individuell", definition: "persönlich, einzigartig" },
    { wort: "inexorabel", definition: "unerbittlich, -" },
    { wort: "infam", definition: "niederträchtig, -" },
    { wort: "infamieren", definition: "verleumden, -" },
    { wort: "infernalis", definition: "höllisch, -" },
    { wort: "inkludieren", definition: "einschließen, einbeziehen" },
    { wort: "inquisitorisch", definition: "untersuchend, -" },
    { wort: "insinuieren", definition: "andeuten, suggerieren" },
    { wort: "inspirieren", definition: "beflügeln, -" },
    { wort: "integrativ", definition: "vereinend, verbindend" },
    { wort: "intellektualisieren", definition: "rationalisieren, intellektuell bearbeiten" },
    { wort: "intellektuell", definition: "geistig, intellektuell" },
    { wort: "interaktiv", definition: "gegenseitig, wechselwirkend" },
    { wort: "interdisziplinär", definition: "fächerübergreifend, -" },
    { wort: "intrigant", definition: "hinterlistig, verschlagen" },
    { wort: "intrigieren", definition: "intrigieren, -" },
    { wort: "intrinsisch", definition: "innerlich, innewohnend" },
    { wort: "introvertiert", definition: "zurückhaltend, nach innen gekehrt" },
    { wort: "invasiv", definition: "eindringend, -" },
    { wort: "ironisch", definition: "spöttisch, sarkastisch" },
    { wort: "ironisieren", definition: "spotten, sarkastisch kommentieren" },
    { wort: "isoliert", definition: "abgeschieden, -" },
    { wort: "iterativ", definition: "wiederholend, -" },
    { wort: "jovial", definition: "gesellig, freundlich" },
    { wort: "judizieren", definition: "urteilen, entscheiden" },
    { wort: "kathartisch", definition: "reinigend, befreiend" },
    { wort: "kathartisch", definition: "reinigend, befreiend" },
    { wort: "klandestin", definition: "heimlich, verdeckt" },
    { wort: "kohärent", definition: "zusammenhängend, stimmig" },
    { wort: "kollektiv", definition: "gemeinschaftlich, gemeinsam" },
    { wort: "komplex", definition: "vielschichtig, facettenreich" },
    { wort: "kompromittieren", definition: "gefährden, bloßstellen" },
    { wort: "konkret", definition: "deutlich, greifbar" },
    { wort: "konsistent", definition: "zusammenhängend, widerspruchsfrei" },
    { wort: "kontemplativ", definition: "nachdenklich, besinnlich" },
    { wort: "kontrastiv", definition: "gegensätzlich, gegensätzlich" },
    { wort: "konzeptionell", definition: "ideell, gedanklich" },
    { wort: "konziliant", definition: "entgegenkommend, versöhnlich" },
    { wort: "kooperativ", definition: "kooperativ, gemeinschaftlich" },
    { wort: "kosmopolitisch", definition: "weltoffen, international" },
    { wort: "kreativ", definition: "einfallsreich, erfinderisch" },
    { wort: "kritisch", definition: "skeptisch, hinterfragend" },
    { wort: "kryptisch", definition: "verschlüsselt, unverständlich" },
    { wort: "kulant", definition: "entgegenkommend, großzügig" },
    { wort: "kursorisch", definition: "oberflächlich, flüchtig" },
    { wort: "labil", definition: "instabil, schwankend" },
    { wort: "lakonisch", definition: "knapp, kurz" },
    { wort: "latent", definition: "verborgen, unausgesprochen" },
    { wort: "legitim", definition: "rechtmäßig, legal" },
    { wort: "liminal", definition: "an der Grenze, -" },
    { wort: "linear", definition: "geradlinig, gradlinig" },
    { wort: "logistisch", definition: "organisatorisch, planerisch" },
    { wort: "lukrativ", definition: "gewinnbringend, profitabel" },
    { wort: "luzide", definition: "klar, deutlich" },
    { wort: "majestätisch", definition: "königlich, erhaben" },
    { wort: "manifestieren", definition: "zeigen, offenbaren" },
    { wort: "manipulativ", definition: "manipulativ, steuernd" },
    { wort: "marginal", definition: "unbedeutend, marginal" },
    { wort: "maskulin", definition: "männlich, männlich" },
    { wort: "matriarchalisch", definition: "weiblich, mütterlich" },
    { wort: "maximal", definition: "höchstens, größtmöglich" },
    { wort: "mediant", definition: "vermittelnd, vermittelnd" },
    { wort: "meditativ", definition: "besinnlich, kontemplativ" },
    { wort: "melancholisch", definition: "schwermütig, düster" },
    { wort: "methodisch", definition: "systematisch, geordnet" },
    { wort: "minimalistisch", definition: "reduziert, schlicht" },
    { wort: "modal", definition: "hinsichtlich der Art und Weise, -" },
    { wort: "monoton", definition: "gleichförmig, eintönig" },
    { wort: "morbide", definition: "krankhaft, düster" },
    { wort: "mundan", definition: "weltlich, alltäglich" },
    { wort: "mysteriös", definition: "geheimnisvoll, rätselhaft" },
    { wort: "mystisch", definition: "geheimnisvoll, esoterisch" },
    { wort: "nachhaltig", definition: "umweltfreundlich, ökologisch" },
    { wort: "nachvollziehbar", definition: "verständlich, plausibel" },
    { wort: "narzisstisch", definition: "selbstverliebt, egozentrisch" },
    { wort: "narzisstisch", definition: "selbstverliebt, egozentrisch" },
    { wort: "nascent", definition: "entstehend, -" },
    { wort: "nativ", definition: "angeboren, -" },
    { wort: "negligieren", definition: "vernachlässigen, übersehen" },
    { wort: "neoklassisch", definition: "klassisch, klassisch" },
    { wort: "neurotisch", definition: "ängstlich, zwanghaft" },
    { wort: "nihilistisch", definition: "lebensverneinend, negativ" },
    { wort: "nivellieren", definition: "ausgleichen, ebnen" },
    { wort: "nomadisch", definition: "wandernd, umherziehend" },
    { wort: "nostalgisch", definition: "sehnsuchtsvoll, wehmütig" },
    { wort: "nostalgisch", definition: "wehmütig, sehnsuchtsvoll" },
    { wort: "notorisch", definition: "allgemein bekannt, -" },
    { wort: "objektiv", definition: "neutral, sachlich" },
    { wort: "obskur", definition: "dubios, undurchsichtig" },
    { wort: "obskur", definition: "zweifelhaft, undurchsichtig" },
    { wort: "obszön", definition: "anstößig, unanständig" },
    { wort: "offensiv", definition: "angriffslustig, aggressiv" },
    { wort: "okkult", definition: "geheimnisvoll, esoterisch" },
    { wort: "omnipräsent", definition: "allgegenwärtig, überall präsent" },
    { wort: "opportun", definition: "gelegenheitsabhängig, situationsabhängig" },
    { wort: "optimal", definition: "ideal, bestmöglich" },
    { wort: "optimistisch", definition: "zuversichtlich, positiv" },
    { wort: "organisch", definition: "naturnah, biologisch" },
    { wort: "orthodox", definition: "traditionell, strenggläubig" },
    { wort: "paradox", definition: "widersprüchlich, gegensätzlich" },
    { wort: "paragon", definition: "Vorbild, Musterbeispiel" },
    { wort: "passiv", definition: "untätig, zurückhaltend" },
    { wort: "pathetisch", definition: "feierlich, dramatisch" },
    { wort: "pedantisch", definition: "pingelig, kleinlich" },
    { wort: "perfektionistisch", definition: "akribisch, pedantisch" },
    { wort: "perplex", definition: "verwirrt, ratlos" },
    { wort: "perspektivisch", definition: "aus einer bestimmten Perspektive, -" },
    { wort: "perzeptiv", definition: "wahrnehmend, empfindsam" },
    { wort: "pessimistisch", definition: "negativ, düster" },
    { wort: "plakativ", definition: "auffällig, markant" },
    { wort: "polarisieren", definition: "spalten, gegensätzliche Meinungen hervorrufen" },
    { wort: "poltern", definition: "laut, brüllen" },
    { wort: "polyvalent", definition: "vielseitig, mehrdeutig" },
    { wort: "populistisch", definition: "volksnah, demagogisch" },
    { wort: "pragmatisch", definition: "praktisch, zweckmäßig" },
    { wort: "präsent", definition: "anwesend, gegenwärtig" },
    { wort: "prätentiös", definition: "übertrieben, angeberisch" },
    { wort: "präzise", definition: "genau, exakt" },
    { wort: "predikativ", definition: "aussagend, bezeichnend" },
    { wort: "primitiv", definition: "einfach, archaisch" },
    { wort: "proaktiv", definition: "handelnd, vorausschauend" },
    { wort: "proklamieren", definition: "verkünden, öffentlich bekanntgeben" },
    { wort: "proliferieren", definition: "verbreiten, sich vermehren" },
    { wort: "provozierend", definition: "herausfordernd, anstößig" },
    { wort: "pseudonym", definition: "Deckname, Künstlername" },
    { wort: "psychedelisch", definition: "bewusstseinsverändernd, halluzinogen" },
    { wort: "publikumswirksam", definition: "wirkungsvoll, effektvoll" },
    { wort: "pulverisieren", definition: "zerstäuben, in Staub verwandeln" },
    { wort: "puristisch", definition: "schlicht, reduziert" },
    { wort: "quintessenz", definition: "Kerngedanke, Essenz" },
    { wort: "radikal", definition: "drastisch, grundlegend" },
    { wort: "reaktionär", definition: "rückwärtsgewandt, konservativ" },
    { wort: "realistisch", definition: "pragmatisch, sachlich" },
    { wort: "redundant", definition: "überflüssig, unnötig" },
    { wort: "reell", definition: "wirklich, tatsächlich" },
    { wort: "reflektieren", definition: "nachdenken, überdenken" },
    { wort: "reizvoll", definition: "ansprechend, attraktiv" },
    { wort: "rekapitulieren", definition: "zusammenfassen, wiederholen" },
    { wort: "resignieren", definition: "aufgeben, resignieren" },
    { wort: "resilient", definition: "belastbar, widerstandsfähig" },
    { wort: "resolut", definition: "entschlossen, energisch" },
    { wort: "resolut", definition: "entschlossen, energisch" },
    { wort: "resonant", definition: "nachhallend, widerhallend" },
    { wort: "revidieren", definition: "überarbeiten, ändern" },
    { wort: "rhetorisch", definition: "sprachgewandt, redekünstlerisch" },
    { wort: "rigoros", definition: "streng, konsequent" },
    { wort: "romantisch", definition: "verträumt, gefühlvoll" },
    { wort: "routiniert", definition: "erfahren, geübt" },
    { wort: "rubrizieren", definition: "kategorisieren, klassifizieren" },
    { wort: "rudimentär", definition: "unvollständig, elementar" },
    { wort: "salient", definition: "hervorstechend, markant" },
    { wort: "sarkastisch", definition: "spöttisch, ironisch" },
    { wort: "selbstbewusst", definition: "selbstsicher, souverän" },
    { wort: "selbstkritisch", definition: "reflektierend, hinterfragend" },
    { wort: "sensibel", definition: "empfindlich, einfühlsam" },
    { wort: "skrupellos", definition: "gewissenlos, rücksichtslos" },
    { wort: "skurril", definition: "bizarr, seltsam" },
    { wort: "solidarisch", definition: "gemeinschaftlich, unterstützend" },
    { wort: "sophistisch", definition: "raffiniert, irreführend" },
    { wort: "souverän", definition: "selbstsicher, überlegen" },
    { wort: "sozial", definition: "gesellschaftlich, gemeinschaftlich" },
    { wort: "spekulativ", definition: "vermutend, hypothetisch" },
    { wort: "spirituell", definition: "geistig, religiös" },
    { wort: "spontan", definition: "impulsiv, unüberlegt" },
    { wort: "stagnieren", definition: "stillstehen, nicht vorankommen" },
    { wort: "stigmatisieren", definition: "brandmarken, diskriminieren" },
    { wort: "stoisch", definition: "gelassen, gleichmütig" },
    { wort: "stoisch", definition: "gelassen, gleichmütig" },
    { wort: "strategisch", definition: "geplant, taktisch" },
    { wort: "subtil", definition: "fein, unauffällig" },
    { wort: "subversiv", definition: "umstürzlerisch, rebellisch" },
    { wort: "superlativ", definition: "höchstes Maß, Spitze" },
    { wort: "surreal", definition: "unwirklich, traumhaft" },
    { wort: "symbolisch", definition: "bedeutungsvoll, allegorisch" },
    { wort: "sympathisch", definition: "angenehm, freundlich" },
    { wort: "synthetisch", definition: "künstlich nachgemacht, -" },
    { wort: "taktisch", definition: "klug, geschickt" },
    { wort: "tendenziös", definition: "einseitig, parteiisch" },
    { wort: "topisch", definition: "aktuell, gegenwärtig" },
    { wort: "transitorisch", definition: "vorübergehend, kurzzeitig" },
    { wort: "transparent", definition: "durchsichtig, klar" },
    { wort: "transzendent", definition: "überirdisch, jenseitig" },
    { wort: "transzendental", definition: "übernatürlich, jenseitig" },
    { wort: "turbulent", definition: "unruhig, bewegt" },
    { wort: "typisch", definition: "charakteristisch, bezeichnend" },
    { wort: "ubiquitär", definition: "allgegenwärtig, überall präsent" },
    { wort: "ultimativ", definition: "letztendlich, endgültig" },
    { wort: "ultrakonservativ", definition: "extrem, reaktionär" },
    { wort: "umfassend", definition: "vollständig, ganzheitlich" },
    { wort: "unikal", definition: "einzigartig, einmalig" },
    { wort: "universell", definition: "allgemeingültig, global" },
    { wort: "unkonkret", definition: "unbestimmt, vage" },
    { wort: "unkonventionell", definition: "ungewöhnlich, originell" },
    { wort: "unprätentiös", definition: "einfach, bescheiden" },
    { wort: "unverfälscht", definition: "authentisch, echt" },
    { wort: "unverhohlen", definition: "offen, unverblümt" },
    { wort: "urban", definition: "städtisch, städtisch" },
    { wort: "utopisch", definition: "idealistisch, unrealistisch" },
    { wort: "vagabundierend", definition: "umherziehend, streunend" },
    { wort: "verbindlich", definition: "verpflichtend, bindend" },
    { wort: "verifizieren", definition: "bestätigen, überprüfen" },
    { wort: "verlässlich", definition: "zuverlässig, vertrauenswürdig" },
    { wort: "vermessen", definition: "vermessen, überheblich" },
    { wort: "versiert", definition: "erfahren, geschickt" },
    { wort: "verspielt", definition: "spielerisch, leichtfertig" },
    { wort: "versponnen", definition: "wirr, verrückt" },
    { wort: "vexierend", definition: "verwirrend, irritierend" },
    { wort: "vigilant", definition: "wachsam, aufmerksam" },
    { wort: "virtuos", definition: "meisterhaft, gekonnt" },
    { wort: "viszeral", definition: "instinktiv, triebhaft" },
    { wort: "vital", definition: "lebendig, energiegeladen" },
    { wort: "vivid", definition: "lebhaft, lebendig" },
    { wort: "vogelfrei", definition: "rechtlos, ungeschützt" },
    { wort: "volatil", definition: "flüchtig, instabil" },
    { wort: "vulgär", definition: "ordinär, geschmacklos" },
    { wort: "wankelmutig", definition: "unbeständig, launisch" },
    { wort: "weltfremd", definition: "unrealistisch, abgehoben" },
    { wort: "willkürlich", definition: "beliebig, zufällig" },
    { wort: "wissbegierig", definition: "neugierig, lernbegierig" },
    { wort: "zivilisiert", definition: "kultiviert, gesittet" },
];

  const zufallsWortAuswählen = () => {
    const zufallsIndex = Math.floor(Math.random() * wortListe.length);
    return wortListe[zufallsIndex];
  };

  const [aktuellesWort, setAktuellesWort] = useState(zufallsWortAuswählen());
  const [istButton1Geklickt, setIstButton1Geklickt] = useState(false);
  const [istButton2Geklickt, setIstButton2Geklickt] = useState(false);

  const handleButton1Click = () => {
    setIstButton1Geklickt(true);
  };

  const handleButton2Click = () => {
    setIstButton2Geklickt(true);
  };

  const handleNewWordClick = () => {
    setAktuellesWort(zufallsWortAuswählen());
    setIstButton1Geklickt(false);
    setIstButton2Geklickt(false);
  };

  return (
    <View style={styleo.container}>
      <ImageBackground source={hintergrundbild} style={styleo.backgroundImage}resizeMode="solid">
        <View style={styleo.textContainer}>
          <Text style={styleo.header}>Dein Wort des Tages{'\n'}</Text>
          
          <Text style={styleo.word}>{aktuellesWort.wort}{'\n'}</Text>
          <Text style={styleo.definition}>
            Was bedeutet das Wort?{'\n'}<Text>{'\n'}</Text> {/* Zeilenumbruch */}<Text style={styleo.underline}>{aktuellesWort.definition}{'\n'}</Text>
          </Text>
          <View style={styleo.buttonContainer}>
            <Button
              title={istButton1Geklickt ? 'verwendet' : 'verwende das Wort'}
              onPress={handleButton1Click}
              color={istButton1Geklickt ? 'gray' : 'darkgreen'}
              disabled={istButton1Geklickt}
            />
            <Button
              title={istButton2Geklickt ? 'verwendet' : 'verwende das Wort'}
              onPress={handleButton2Click}
              color={istButton2Geklickt ? 'gray' : 'darkgreen'}
              disabled={!istButton1Geklickt || istButton2Geklickt}
            />
          </View>
          <Button
            title="Neues Wort gefällig?"
            onPress={handleNewWordClick}
          />
          {istButton1Geklickt && istButton2Geklickt && (
            <Text style={styleo.congratulations}>Dein Tagessoll ist erfüllt. Glückwunsch!</Text>
          )}
        </View>
      </ImageBackground>
    </View>
  );
}
const styleo = StyleSheet.create({
  container: {
    flex: 1,
  },
  backgroundImage: {
    flex: 1,
    resizeMode: 'cover',
    justifyContent: 'center',
  },
  textContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    padding: 20,
    margin: 20,
    borderRadius: 10,
  },
  header: {
    fontSize: 24,
    textAlign: 'center',
    marginBottom: 20,
    textDecorationLine: 'underline',
  },
  word: {
    fontSize: 32,
    fontFamily: 'Harrington',
    textAlign: 'center',
  },
  definition: {
    fontSize: 18,
    textAlign: 'center',
    marginBottom: 20,
  },
  underline: {
    textDecorationLine: 'underline',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  congratulations:{
    marginTop: 20,
    textAlign: 'center',
    fontSize: 16,}
});
